pub struct BuiltinProtocol {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub accent: &'static str,
    pub schema_version: i64,
    pub schema: &'static str,
}

pub fn builtins() -> [BuiltinProtocol; 11] {
    [
        BuiltinProtocol {
            id: "pro-cell-thaw",
            name: "细胞复苏",
            category: "细胞培养",
            accent: "#167c80",
            schema_version: 2,
            schema: r#"{"schemaVersion":2,"blocks":["37℃ 水浴复苏","5× 稀释并 1000 rpm 离心 5 min","重悬后置入 CO₂ 培养箱"],"fields":[{"key":"cell_name","label":"细胞名称","kind":"text","required":true}],"template":"日期：{{date}}\n细胞名称：{{cell_name}}\n\n1. 取出液氮中的 {{cell_name}} 冻存管，用薄膜手套包裹，于37℃水浴锅中摇动，直至培养基融化成可流动液体状。\n\n2. 超净台用紫外照射至少15min后，打开冻存管，吸出细胞悬液装入15ml离心管中，并以培养基5×稀释，离心1000rpm，5min。\n\n3. 弃去离心后的培养基上清，取1～1.5 ml 到离心管中，轻轻吹打使细胞重悬。吸出细胞悬液于培养瓶或培养皿中，加入培养基。放CO2培养箱中进行培养。","execution":{"eventType":"thaw","inputTypes":[],"outputType":"CELL","outputMode":"one"}}"#,
        },
        BuiltinProtocol {
            id: "pro-cell-passage",
            name: "细胞传代",
            category: "细胞培养",
            accent: "#167c80",
            schema_version: 3,
            schema: r#"{"schemaVersion":3,"blocks":["选择上一代细胞","选择贴壁或悬浮传代","按完整 SOP 处理并记录输出"],"fields":[{"key":"input_sample","label":"上一步 Cell","kind":"samples"},{"key":"cell_name","label":"新细胞名称","kind":"text"},{"key":"culture_mode","label":"培养方式","kind":"select","required":true,"options":["贴壁","悬浮"]},{"key":"output_count","label":"输出数量","kind":"number","required":true}],"templateSelector":"culture_mode","templateVariants":{"贴壁":"日期：{{date}}\n培养方式：{{culture_mode}}\n\n1. 吸除或倒掉瓶内旧培养液。\n2. PBS洗2～3次。\n3. 加入适量胰蛋白酶，轻摇使消化液流遍细胞表面。\n4. 放入培养箱消化2～5 min。\n5. 显微镜下观察，待胞质回缩、细胞间隙增大后立即终止消化，可拍打培养皿或培养瓶底部。\n6. 吸除或倒掉胰酶，加少许含血清培养液终止消化；反复轻柔吹打瓶壁细胞，从一边到底部另一边，确保细胞全部脱壁形成悬液。\n7. 计数，分别接种新的培养瓶。","悬浮":"日期：{{date}}\n培养方式：{{culture_mode}}\n\n悬浮细胞可采用离心收集后传代或直接传代。\n\n离心法：\n1. 将细胞连同培养液转移至15 ml离心管。\n2. 1000 rpm，离心5 min。\n3. 弃上清，加入新培养液吹打成细胞悬液。\n4. 计数，分别接种新的培养瓶。\n\n直接传代法：\n待悬浮细胞慢慢沉淀到瓶底，吸掉1/2～2/3上清，用吸管吹打成细胞悬液后传代。"},"execution":{"eventType":"passage","inputTypes":["CELL"],"outputType":"CELL","outputMode":"count","consumptionPolicy":"consume"}}"#,
        },
        BuiltinProtocol {
            id: "pro-cell-plating",
            name: "细胞铺板",
            category: "细胞培养",
            accent: "#167c80",
            schema_version: 4,
            schema: r#"{"schemaVersion":4,"blocks":["选择细胞","选择器皿类型与孔板规格","完成铺板"],"fields":[{"key":"input_sample","label":"输入 Cell","kind":"samples"},{"key":"cell_name","label":"新细胞名称（未选择输入时）","kind":"text"},{"key":"container_type","label":"器皿类型","kind":"select","required":true,"options":["孔板","培养皿"]},{"key":"plate_format","label":"孔板规格","kind":"select","options":["6孔板","12孔板","24孔板","48孔板","96孔板","384孔板"],"visibleWhen":{"key":"container_type","value":"孔板"}}],"template":"日期：{{date}}\n器皿类型：{{container_type}}\n孔板规格：{{plate_format}}\n\n1. 选择待铺板细胞。\n2. 将细胞接种到选定的器皿中。","execution":{"eventType":"plating","inputTypes":["CELL"],"outputMode":"plate_or_dish"}}"#,
        },
        BuiltinProtocol {
            id: "pro-cell-treatment",
            name: "细胞加刺激",
            category: "细胞培养",
            accent: "#167c80",
            schema_version: 5,
            schema: r#"{"schemaVersion":5,"blocks":["选择同一类型的一个或多个 Sample","填写该类型对应的刺激条件","核对并生成 Record"],"fields":[{"key":"treatment_groups","label":"孔板刺激分组","kind":"plate_layout","visibleForInputTypes":["PLATE"]},{"key":"treatment_type","label":"刺激类型","kind":"text","visibleForInputTypes":["CELL","DISH","WELL"]}],"template":"日期：{{date}}\n输入 Sample：{{input_sample_summary}}\n\n刺激设置：\n{{treatment_summary}}\n\n实验过程：\n1. 核对输入 Sample 和刺激条件。\n2. 按上述设置完成刺激。\n3. 记录实际操作、偏差和观察结果。","execution":{"eventType":"treatment","inputSource":"experiment_samples","inputCardinality":"many","inputTypePolicy":"uniform","inputTypes":["CELL","PLATE","DISH","WELL"],"outputMode":"plate_wells","consumptionPolicy":"non_destructive"}}"#,
        },
        BuiltinProtocol {
            id: "pro-rna",
            name: "RNA Extraction — Trizol",
            category: "分子生物学",
            accent: "#6957e8",
            schema_version: 2,
            schema: r#"{"schemaVersion":3,"blocks":["选择 Experiment Sample","Trizol 裂解","相分离","RNA 沉淀与乙醇洗涤","复溶"],"fields":[{"key":"resuspension_volume","label":"RNase-free 水复溶体积（μL）","kind":"number","required":true,"defaultValue":"20"},{"key":"storage","label":"RNA 后续处理","kind":"select","required":true,"options":["立即逆转录","-80℃ 保存"]}],"template":"日期：{{date}}\n输入样本：{{input_sample_summary}}\nRNase-free 水复溶体积：{{resuspension_volume}} μL\n后续处理：{{storage}}\n\n1. 去除培养基，PBS 洗1遍，加入1 ml Trizol裂解液，反复吹打、刮擦，将裂解液转入无RNase EP管。\n2. 加入0.2 ml氯仿，颠倒摇匀，冰上静置5分钟，12000 g离心10分钟。\n3. 取上层水相至新无RNase EP管，加入等体积异丙醇，静置10分钟，12000 g离心10分钟。\n4. 去除上清，加入1 ml预冷75%乙醇轻振，7500 g离心5分钟。\n5. 小心除去上清，乙醇干燥后加入 {{resuspension_volume}} μL RNase-free水，静置5分钟使RNA溶解。","execution":{"eventType":"rna_extraction","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["CELL","WELL","DISH"],"outputType":"RNA","outputMode":"per_input","consumptionPolicy":"consume"}}"#,
        },
        BuiltinProtocol {
            id: "pro-rt",
            name: "Reverse Transcription — PrimeScript",
            category: "分子生物学",
            accent: "#6957e8",
            schema_version: 2,
            schema: r#"{"schemaVersion":3,"blocks":["选择 RNA","去除基因组 DNA","逆转录反应","保存 cDNA"],"fields":[{"key":"rna_amount","label":"每个反应 RNA 用量（μg）","kind":"number","required":true,"defaultValue":"1.0"},{"key":"extra_reactions","label":"额外反应数","kind":"number","required":true,"defaultValue":"2"}],"template":"日期：{{date}}\n输入 RNA：{{input_sample_summary}}\n每个反应 RNA：{{rna_amount}} μg；额外反应：{{extra_reactions}}。\n\n1. gDNA去除：5×gDNA Eraser Buffer 2.0 μL、gDNA Eraser 1.0 μL、Total RNA {{rna_amount}} μg，以RNase Free dH2O补至10 μL；42℃ 2 min，4℃保持。\n2. 逆转录：步骤1反应液10 μL、PrimeScript RT Enzyme Mix I 1 μL、RT Primer Mix 1 μL、5×PrimeScript Buffer 2 4 μL、RNase Free dH2O 4 μL。\n3. 37℃ 15 min，85℃ 5 sec，4℃保持。产物直接用于qRT-PCR，或-20℃短期、-80℃长期保存。","execution":{"eventType":"reverse_transcription","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["RNA"],"outputType":"CDNA","outputMode":"per_input","consumptionPolicy":"aliquot"}}"#,
        },
        BuiltinProtocol {
            id: "pro-qpcr",
            name: "SYBR Green qPCR",
            category: "分子生物学",
            accent: "#6957e8",
            schema_version: 3,
            schema: r#"{"schemaVersion":4,"blocks":["选择 cDNA 与 Targets","反应体系","扩增程序","Plate Mapping 与 Raw Cq"],"fields":[{"key":"assay_items","label":"Targets（逗号分隔）","kind":"text","required":true}],"template":"日期：{{date}}\n输入 cDNA：{{input_sample_summary}}\nTargets：{{assay_items}}\n\n每个25 μL反应：SYBR Premix Ex TaqII 12.5 μL，正向引物1.0 μL，反向引物1.0 μL，cDNA 2.0 μL，RNase Free dH2O 8.5 μL。\n程序：95℃ 30 sec；40个循环（95℃ 5 sec，60℃ 30–60 sec）；Dissociation。\n\nPlate Mapping 与 Raw Cq 作为本 Record 的终末检测数据保存，不创建新的 Sample。","execution":{"eventType":"qpcr","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["CDNA"],"outputMode":"none","consumptionPolicy":"aliquot"},"terminalAssay":{"itemLabel":"Target / Gene","metricKey":"cq","metricLabel":"Cq","plateModels":["96","384"]}}"#,
        },
        BuiltinProtocol {
            id: "pro-wb",
            name: "Western Blot",
            category: "分子生物学",
            accent: "#c4573b",
            schema_version: 1,
            schema: r#"{"schemaVersion":2,"blocks":["样品准备","配胶","电泳与转膜","封闭与抗体孵育","显影"],"fields":[{"key":"target_proteins","label":"目的蛋白（逗号分隔）","kind":"text","required":true},{"key":"gel_percentage","label":"分离胶浓度（%）","kind":"number","required":true,"defaultValue":"10"},{"key":"primary_antibody","label":"一抗及稀释比例","kind":"text","required":true},{"key":"secondary_antibody","label":"二抗及稀释比例","kind":"text","required":true},{"key":"exposure_time","label":"曝光时间","kind":"text"}],"template":"日期：{{date}}\n输入样本：{{input_sample_summary}}\n目的蛋白：{{target_proteins}}\n\n1. 去除培养基，PBS轻柔漂洗3次。RIPA与PMSF按100:1配制，每孔加入预冷裂解液，冰上裂解10分钟，刮取并转入1.5 mL离心管，12000 g、4℃离心5分钟。G250法定量，调平浓度，加入5×SDS-PAGE上样缓冲液，100℃煮样10分钟。\n2. 配制 {{gel_percentage}}% 分离胶及浓缩胶。\n3. 80 V电泳至分离胶后调至120 V；PVDF膜甲醇活化，100 V湿转1小时。\n4. 封闭后孵育一抗 {{primary_antibody}}，PBST洗涤；孵育二抗 {{secondary_antibody}}，再次洗涤。\n5. ECL显影，曝光时间：{{exposure_time}}。显影图像作为Result/Attachment保存。","execution":{"eventType":"western_blot","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["CELL","WELL","DISH"],"outputType":"PROTEIN","outputMode":"per_input","resultTypes":["western_blot_image"],"consumptionPolicy":"consume"}}"#,
        },
        BuiltinProtocol {
            id: "pro-supernatant",
            name: "培养上清收集",
            category: "分子生物学",
            accent: "#2c77b8",
            schema_version: 1,
            schema: r#"{"schemaVersion":2,"blocks":["选择培养对象","收集上清","澄清离心","分装保存"],"fields":[{"key":"collection_time","label":"收集时间点","kind":"text","required":true},{"key":"collection_volume","label":"每个样本收集体积（μL）","kind":"number","required":true},{"key":"storage","label":"保存方式","kind":"select","required":true,"options":["立即检测","-80℃ 保存"]}],"template":"日期：{{date}}\n输入培养对象：{{input_sample_summary}}\n收集时间点：{{collection_time}}；每个样本体积：{{collection_volume}} μL；保存：{{storage}}。\n\n1. 收集各培养对象的细胞培养上清。\n2. 300 g离心10分钟，去除沉淀物。\n3. 上清可立即检测，或分装后置于-80℃保存。","execution":{"eventType":"supernatant_collection","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["CELL","WELL","DISH"],"outputType":"SUP","outputMode":"per_input","consumptionPolicy":"non_destructive"}}"#,
        },
        BuiltinProtocol {
            id: "pro-elisa",
            name: "ELISA — 细胞因子",
            category: "分子生物学",
            accent: "#2c77b8",
            schema_version: 2,
            schema: r#"{"schemaVersion":3,"blocks":["选择培养上清与 Analytes","标准品与试剂准备","抗体孵育与洗板","TMB 显色与双波长读数"],"fields":[{"key":"assay_items","label":"Analytes（逗号分隔）","kind":"text","required":true},{"key":"sample_dilution","label":"样本稀释倍数","kind":"number","required":true,"defaultValue":"1"},{"key":"reference_wavelength","label":"参考波长","kind":"select","required":true,"options":["570 nm","630 nm"]}],"template":"日期：{{date}}\n输入上清：{{input_sample_summary}}\nAnalytes：{{assay_items}}；样本稀释倍数：{{sample_dilution}}；参考波长：{{reference_wavelength}}。\n\n1. 样本准备：细胞培养上清300 g离心10分钟去除沉淀，可立即检测或分装后-80℃储存。\n2. 按试剂盒配制1×洗液、1×检测缓冲液；检测抗体与链霉亲和素按1:100稀释并在30分钟内使用。\n3. 重溶细胞因子标准品，以细胞培养基进行1:1系列稀释，并设置零浓度标准品。\n4. 每孔加入300 μL洗液浸泡30秒并拍干；标准品孔加入100 μL标准品，样本孔加入80 μL检测缓冲液和20 μL样本。\n5. 每孔加入50 μL检测抗体，封板后300 rpm室温振荡孵育1.5小时；每孔300 μL洗液洗板6次。\n6. 每孔加入100 μL稀释的链霉亲和素，封板后300 rpm室温振荡孵育30分钟，再洗板6次。\n7. 每孔加入100 μL TMB，室温孵育5–30分钟；快速加入100 μL终止液。\n8. 立即测定450 nm及 {{reference_wavelength}}。Plate Mapping 与 Raw OD 作为本 Record 的终末检测数据保存，不创建新的 Sample。","execution":{"eventType":"elisa","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["SUP"],"outputMode":"none","consumptionPolicy":"aliquot"},"terminalAssay":{"itemLabel":"Analyte","metricKey":"od450","metricLabel":"OD450","plateModels":["96"]}}"#,
        },
        BuiltinProtocol {
            id: "pro-cck8",
            name: "CCK-8 细胞增殖/毒性实验",
            category: "细胞实验",
            accent: "#d8842f",
            schema_version: 1,
            schema: r#"{"schemaVersion":2,"blocks":["选择细胞孔与 Conditions","加入 CCK-8","培养箱孵育","450 nm 读数"],"fields":[{"key":"assay_items","label":"Conditions（逗号分隔）","kind":"text","required":true},{"key":"assay_mode","label":"实验类型","kind":"select","required":true,"options":["细胞增殖","细胞毒性"]},{"key":"cell_count","label":"每孔细胞数","kind":"number","required":true},{"key":"culture_volume","label":"每孔培养体积（μL）","kind":"number","required":true,"defaultValue":"100"},{"key":"cck8_volume","label":"每孔 CCK-8 体积（μL）","kind":"number","required":true,"defaultValue":"10"},{"key":"incubation_time","label":"CCK-8 孵育时间（小时）","kind":"number","required":true,"defaultValue":"1"},{"key":"reference_wavelength","label":"参考波长（可选）","kind":"text","defaultValue":"650 nm"}],"template":"日期：{{date}}\n输入细胞孔：{{input_sample_summary}}\nConditions：{{assay_items}}\n实验类型：{{assay_mode}}；每孔细胞数：{{cell_count}}；培养体积：{{culture_volume}} μL；CCK-8：{{cck8_volume}} μL；孵育：{{incubation_time}}小时。\n\n1. 细胞增殖实验通常每孔加入100 μL、2000个细胞；细胞毒性实验通常每孔加入100 μL、5000个细胞，具体数量根据细胞大小和增殖速度调整，并按实验需要给予0–10 μL药物刺激。\n2. 每孔加入相当于培养体积10%的CCK-8溶液。可设置只有培养液和CCK-8、没有细胞的空白孔；药物可能干扰时，设置培养液、药物和CCK-8但没有细胞的空白孔。\n3. 培养箱内继续孵育0.5–4小时，多数情况1小时；初次实验可在0.5、1、2、4小时分别检测以选择合适时间点。\n4. 450 nm测定吸光度；无450 nm滤光片时可用420–480 nm，可用大于600 nm波长作双波长参考。\n5. 注意96孔板边缘蒸发、还原剂干扰及读数前孔内气泡。Plate Mapping 与 Raw OD 作为本 Record 的终末检测数据保存，不创建新的 Sample。","execution":{"eventType":"cck8","inputSource":"experiment_samples","inputCardinality":"many","inputTypes":["WELL"],"outputMode":"none","consumptionPolicy":"consume"},"terminalAssay":{"itemLabel":"Condition","metricKey":"od450","metricLabel":"OD450","plateModels":["96"]}}"#,
        },
    ]
}
